apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telegraf-config
data:
  telegraf.conf: |        
    # Configuration for telegraf agent
    [agent]
    # Default data collection interval for all inputs
    interval = {{ .Values.CollectionInterval | quote }}

    {{- if .Values.Databases.MI }}
    [[inputs.sqlserver]]
    database_type = "AzureSQLManagedInstance"
    servers = [
    {{- range .Values.Databases.MI }}
      {{ . | quote }},
    {{- end }}    
    ]
    {{- end }}

    {{- if .Values.Databases.DB }}
    [[inputs.sqlserver]]
    database_type = "AzureSQLDB"
    servers = [
    {{- range .Values.Databases.DB }}
      {{ . | quote }},
    {{- end }}    
    ]
    {{- end }}

    {{- if .Values.Databases.VM }}
    [[inputs.sqlserver]]
    database_type = "SQLServer"
    servers = [
    {{- range .Values.Databases.VM }}
      {{ . | quote }},
    {{- end }}    
    ]
    {{- end }}

    [[outputs.file]]
      files = ["stdout","/mnt/logs/metrics.out"]
      ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
      data_format = "json"
      json_timestamp_units = "1ms"